### ISSUE TITLE
Provide the schema for IDEs

### ISSUE THREAD

**Issue by Sacro** [budimanjojo/talhelper#189]
It'd be really nice to have editor assistance, is it possible to have JSON/YAML schema files?

**Comment by budimanjojo** [comment]
@Sacro Yeah indeed it is. Do you know any good tool to do this?

**Comment by budimanjojo** [comment]
I think I'm going with https://github.com/invopop/jsonschema as I haven't find alternative for it, but it doesn't support `yaml` tag which is what I'm using but still not too bad to add it.

**Comment by budimanjojo** [comment]
@Sacro I just created a PR for this feature, everything seems good so far so I might merge this tomorrow after more testing. See if there's anything you'd like to add. Thank you for the suggestions!

**Comment by Sacro** [comment]
That looks great, I did try it myself but I had all the `yaml` tags converted to `json` for some reason, and I couldn't get the tests to pass.

One other next feature would be filing it with https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md so it gets picked up more automatically!

**Comment by budimanjojo** [comment]
Yeah `yaml` tag is needed both upstream Talos and here so I used `Reflector.FieldNameTag = "yaml"` instead.

I found a problem with `nodes[].installDiskSelector.size` because there's something being done internally by upstream to make a struct become string. I was thinking to ignore that field but it's not a solution so I just leave it and probably find a way to fix it in the future. Another thing is fields from upstream doesn't have any description/example because they're using comments and not `tag`.

I'll try to create a PR to SchemaStore and hopefully it can get merged. Thanks!

**Comment by Sacro** [comment]
If you need to link to talos things, you can use [$ref](https://json-schema.org/draft-06/draft-wright-json-schema-01#rfc.section.8)

They have a schema file at https://github.com/siderolabs/talos/blob/main/pkg/machinery/config/types/v1alpha1/schemas/v1alpha1_config.schema.json

**Comment by budimanjojo** [comment]
@Sacro Thanks for the info! I see what I can do to it.

Btw the schemastore PR got merged :smile: https://github.com/SchemaStore/schemastore/pull/3352
