### ISSUE TITLE
"key/cert combination should not be empty" when generate worker.yaml

### ISSUE THREAD

**Issue by soulwhisper** [budimanjojo/talhelper#269]
It keeps reporting "key/cert combination should not be empty" when using commands below. The first 3 controlPlane yaml generated successfully.
```bash
talhelper genconfig \
	--config-file talconfig.yaml \
	--env-file talenv.yaml \
	--secret-file talsecret.yaml
```
My talconfig link [here](https://github.com/soulwhisper/homelab/blob/main/talos/talconfig.yaml)

**Comment by budimanjojo** [comment]
The error came from upstream config validation and doesn't seem helpful but the error is caused by this patch: https://github.com/soulwhisper/homelab/blob/a2f21332f2ca6dfc62649963f1fde38c74c70e0f/talos/talconfig.yaml#L159

I think it's because the worker node doesn't have etcd configuration. I'll take a look when I'm free later

**Comment by soulwhisper** [comment]
I managed to solve this, correction reflects in my configs. It happens when I put some controlPlane exclusive configs into global patches, yet the error not reflect this.

**Comment by soulwhisper** [comment]
Thank you for replying, correction reflects in my configs.
