### ISSUE TITLE
compute-plane config doesn't contain `cluster.clusterName`

### ISSUE THREAD

**Issue by cwrau** [budimanjojo/talhelper#367]
This results in the machine not displaying the clusterName on the dashboard, instead it just prints `n/a`

Currently, we fix this with the following;

```jsonpatch
patches:
  - |-
    - op: add
      path: /cluster/clusterName
      value: <clusterName>
```

**Comment by budimanjojo** [comment]
Thanks for the provided information.
I just tried with your `talconfig.yaml` file, the `cluster.clusterName` is not set for the `compute-plane-0` is because that node is a worker node.

I don't know the specific reason but seems like the API from Talos doesn't set `cluster.clusterName` for non controlplane nodes. You can verify this with `talosctl gen config management-cluster https://3.3.3.3:6443` and see that the generated `worker.yaml` file also doesn't have `cluster.clusterName` set.

My guess is because you don't talk to worker node directly using `talosconfig` file so it just doesn't set it by default.

I can explicitly set it with `talhelper` if you really need it, but I need the reason from you. And I think this makes more sense to be fixed (if you really think it is a problem) from upstream instead of `talhelper`.

**Comment by cwrau** [comment]
> Thanks for the provided information.
> I just tried with your `talconfig.yaml` file, the `cluster.clusterName` is not set for the `compute-plane-0` is because that node is a worker node.
> 
> I don't know the specific reason but seems like the API from Talos doesn't set `cluster.clusterName` for non controlplane nodes. You can verify this with `talosctl gen config management-cluster https://3.3.3.3:6443` and see that the generated `worker.yaml` file also doesn't have `cluster.clusterName` set.
> 
> My guess is because you don't talk to worker node directly using `talosconfig` file so it just doesn't set it by default.

Oh, I didn't know that 🤔 

> I can explicitly set it with `talhelper` if you really need it, but I need the reason from you. And I think this makes more sense to be fixed (if you really think it is a problem) from upstream instead of `talhelper`.

No, it's no problem, just for aesthetics, I just thought the problem was with this tool not setting something

Great tool btw! 😁
