### ISSUE TITLE
Use importable (cobra-)run functions

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#493]
It would be nice if the functions under cobra-run, are split-off into a separately exported functions.

That allows custom go tooling, to call the functions (and send them their args), as well.
Which would now basically require writhing custom variants/copies of those run sections.

Its a relatively minor change to tooling, but significantly increases usability.
I'm okey with sending in the PR myself btw :)

---

Note, i'm aware there is more to things at times than just the run section, primarily setting/getting of `flags`, but thats relatively manageable in scope compared to the, sometimes extensive, run sections

**Comment by budimanjojo** [comment]
Do you mean exporting the subcommands of the program? I'm not sure if this is a good idea because it's very program specific functions and they're mostly just calling the exported functions from the `pkg` directory anyway. Maybe if you can state your use case for it might give me better explanation because I don't quite understand your request tbh.

**Comment by Ornias1993** [comment]
We're moving some tooling from bash to go.
But we've since gone over it more completely and you're correct: it wouldn't really solve much at all, as everything is too interconnected. A simple export wouldn't do anything of relevance!

Sorry for the bother!
