### ISSUE TITLE
Feature Request: auto inject generated schematic ID as node annotation

### ISSUE THREAD

**Issue by JJGadgets** [budimanjojo/talhelper#550]
Allows for easier SUC usage for clusters with different schematic IDs across nodes, or for forgetful people like me to avoid forgetting to change a hardcoded value (in SUC config)

**Comment by budimanjojo** [comment]
Thank you for the FR! Since Talos currently only supports `nodeLabels` and not `nodeAnnotations`, so it's not currently possible because of the 63 string length limit of labels in k8s.

But it seems like there's already work in progress in the upstream: https://github.com/siderolabs/talos/issues/9089

So we'll just wait and see how the upstream will handle this and maybe Talhelper doesn't need to do anything.

**Comment by budimanjojo** [comment]
https://github.com/budimanjojo/talhelper/pull/577 this allows user to set node annotations.
Afaik from the PR from upstream above, node annotations containing schematic ID should be done automatically by `talosctl`?
I need confirmation from those who have tried the 1.8 alpha version or just wait until 1.8 stable got released.

**Comment by PrivatePuffin** [comment]
@budimanjojo Talos 1.8 adds node annotations with schematic ids automatically.
So this can be closed

**Comment by budimanjojo** [comment]
Thanks for the information! Closing now.
