### ISSUE TITLE
Remove hostDNS from Talos config

### ISSUE THREAD

**Issue by Sapp00** [budimanjojo/talhelper#578]
Hello,

I am using talhelper for a while now, but recently discovered a bug/incompatibility issue with Talos v1.7.6. It seems like "hostDNS" is not supported anymore, but it is being added automatically by talhelper even when not in the `talconfig.yaml`. 

It throws the following error:
`error applying new configuration: 1 error occurred:
        * 10.10.10.22: rpc error: code = InvalidArgument desc = unknown keys found during decoding:
machine:
    features:
        hostDNS:
            enabled: true
`

Workaround is to remove the respective entry from the generated config files.

**Comment by budimanjojo** [comment]
`hostDNS` is new feature of Talos v1.7. And Talhelper doesn't add that but it's added by default by Talos API when version is above 1.7. It's the same behavior when you do `talosctl gen config`.

I think the problem is you're using very old version of `talosctl`. Try updating your `talosctl` to latest version.

**Comment by budimanjojo** [comment]
This is the relavant lines from upstream that does this: https://github.com/siderolabs/talos/blob/bc8bf9e8a865473011dcf5ad2df08c8ff1af5110/pkg/machinery/config/generate/init.go#L96-L101

**Comment by budimanjojo** [comment]
I'm going to close this issue because of inactivity. Feel free to re open if you are not satisfied with my answer. Thank you.
