### ISSUE TITLE
unknown flag: --stage

### ISSUE THREAD

**Issue by runningman84** [budimanjojo/talhelper#780]
It would be cool to also support the stage parameter for the gencommand upgrade. Btw. I also had to use the --reboot-mode parameter.

**Comment by budimanjojo** [comment]
Hi @runningman84!

Do you already know the `--extra-flags` flag that you can use on all `gencommand` subcommands?
You can do it like so: `talhelper gencommand upgrade -n <nodename> --extra-flags "--stage --reboot-mode powercycle"`.

**Comment by runningman84** [comment]
Hmm okay I used gencommand the wrong way but if you pass everything as one single string parameter the comma char is lost

````
task: [reset-wipe-maintenance-mode] talhelper gencommand reset --extra-flags "--system-labels-to-wipe=EPHEMERAL,STATE --reboot"
talosctl reset --talosconfig=./clusterconfig/talosconfig --nodes=10.0.30.81 --system-labels-to-wipe=EPHEMERAL STATE --reboot;
talosctl reset --talosconfig=./clusterconfig/talosconfig --nodes=10.0.30.82 --system-labels-to-wipe=EPHEMERAL STATE --reboot;
talosctl reset --talosconfig=./clusterconfig/talosconfig --nodes=10.0.30.83 --system-labels-to-wipe=EPHEMERAL STATE --reboot;
talosctl reset --talosconfig=./clusterconfig/talosconfig --nodes=10.0.30.84 --system-labels-to-wipe=EPHEMERAL STATE --reboot;
````

**Comment by budimanjojo** [comment]
Thank you! Didn't think about that but this works (although very ugly): `talhelper gencommand reset --extra-flags \"--system-labels-to-wipe=EPHEMERAL,STATE\" --extra-flags --reboot`

This is due to the `--extra-flags` is using `StringSliceVar` of `cobra` and the string will be converted into slice by the code based on comma (see https://github.com/spf13/pflag/issues/57)

**Comment by runningman84** [comment]
okay thanks for the tip
